-- Generated by scripts/hypr2lua.
-- Source: omarchy-phosphor-os-theme/hyprland.conf

local activeBorderColor = "rgba(11ff25dd)"
local inactiveBorderColor = "rgba(4c6b47dd)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 6,
    gaps_out = 12,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 4,
    active_opacity = 0.92,
    inactive_opacity = 0.78,
    blur = {
      enabled = true,
      size = 8,
      passes = 4,
      ignore_opacity = true,
      new_optimizations = true,
      xray = true,
      noise = 0.018,
      contrast = 1.12,
      brightness = 0.75,
      vibrancy = 0.25,
      vibrancy_darkness = 0.82,
      popups = true,
      popups_ignorealpha = 0.22,
    },
    shadow = {
      enabled = true,
      range = 22,
      scale = 2.0,
      render_power = 5,
      color = "rgba(11ff2570)",
      color_inactive = "rgba(0d1618d8)",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("easeInOutQuant", { type = "bezier", points = { { 0.76, 0 }, { 0.24, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("silk_drop", { type = "bezier", points = { { 0.28, 1.54 }, { 0.70, 1 } } })

hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 2.2,
  bezier = "silk_drop",
  style = "slidevert",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 1.5,
  bezier = "silk_drop",
})
